[tool.poetry]
name = "propan"
version = "0.0.6.8"
description = "Simple and fast framework to create message brokers based microservices"
readme = "README.md"
homepage = "https://github.com/Lancetnik/Propan"
keywords = ["rabbitmq", "framework", "message brokers"]

authors = [
    'Pastukhov Nikita <diementros@yandex.ru>'
]

classifiers = [
    'Development Status :: 3 - Alpha',
    'Programming Language :: Python',
    'Programming Language :: Python :: Implementation :: CPython',
    'Programming Language :: Python :: Implementation :: PyPy',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3 :: Only',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Intended Audience :: Developers',
    'Intended Audience :: Information Technology',
    'Intended Audience :: System Administrators',
    'Topic :: Software Development :: Libraries :: Python Modules',
    'Topic :: Internet',
]


[tool.poetry.urls]
"Source" = "https://github.com/Lancetnik/Propan"
"Tracker" = "https://github.com/Lancetnik/Propan/issues"
"Documentation" = "https://github.com/Lancetnik/Propan"


[tool.poetry.scripts]
propan = "propan:run"

[tool.poetry.dependencies]
python = ">3.8,<4"
pydantic = "^1.8.2"
asgiref = "^3.6"
watchgod = "*"
click = "*"

"aio-pika" = { version=">9", optional= true, extras = ["async-rabbit"] }

[tool.poetry.extras]
"async-rabbit" = ["aio-pika"]

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-asyncio = "*"
python-lsp-server = "*"
importlib_metadata = "*"
flake8 = "*"
flake8-isort = "*"
autopep8 = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
