site_name: Propan
site_description: Propan is a modern framework for building Applications based on Messaging Architecture.
site_url: https://lancetnik.github.io/Propan/
dev_addr: 0.0.0.0:8000

repo_name: lancetnik/propan
repo_url: https://github.com/lancetnik/propan
edit_uri: https://github.com/lancetnik/propan

copyright: Copyright &copy; 2019 - 2023 Pastukhov Nikita

docs_dir: docs

extra_css:
  - assets/stylesheets/termynal.css
  - assets/stylesheets/custom.css

extra_javascript:
  - assets/javascripts/termynal.js
  - assets/javascripts/custom.js

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - navigation.path
    - navigation.top
  i18n:
    prev: 'Previous'
    next: 'Next'
  icon:
    repo: fontawesome/brands/github
  logo: assets/img/logo-white.png
  favicon: assets/img/favicon.png

plugins:
  - search
  - markdownextradata:
      data: data
  - i18n:
      default_language: en
      docs_structure: folder
      material_alternate: true
      languages:
        en:
          name: English
          build: true
        ru:
          name: Русский
          build: true

markdown_extensions:  # do not reorder
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - mdx_include:
      base_path: .
  - tables
  - admonition
  - codehilite
  - extra
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format ''
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji ""
      emoji_generator: !!python/name:materialx.emoji.to_svg ""
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lancetnik/propan
    - icon: simple/telegram
      link: https://t.me/propan_python

nav:
  - Welcome: index.md
  - Getting Started:
    - Hello, Propan!: 2_getting_started/1_quick-start.md
    - CLI Tool: 2_getting_started/2_cli.md
    - Application: 2_getting_started/3_app.md
    - Brokers:
      - Basics: 2_getting_started/4_broker/1_index.md
      - Routing and Errors: 2_getting_started/4_broker/2_routing.md
      - Incoming Messages: 2_getting_started/4_broker/3_type-casting.md
      - Publish Messages: 2_getting_started/4_broker/4_publishing.md
      - RPC over MQ: 2_getting_started/4_broker/5_rpc.md
    - Dependency Injection:
      - Depends: 2_getting_started/5_dependency/1_di-index.md
      - Context: 2_getting_started/5_dependency/2_context.md
    - Lifespan: 2_getting_started/6_lifespans.md
    - Testing: 2_getting_started/7_testing.md
    - Logging: 2_getting_started/8_logging.md
  - RabbitMQ:
    - Routing: 3_rabbit/1_routing.md
    - Exchanges: 3_rabbit/2_exchanges.md
    - Queues and Bindings: 3_rabbit/3_queues.md
    - Rabbit Pubslishing: 3_rabbit/4_publishing.md
    - Examples:
      - Direct Exchange: 3_rabbit/5_examples/1_direct.md
      - Fanout Exchange: 3_rabbit/5_examples/2_fanout.md
      - Topic Exchange: 3_rabbit/5_examples/3_topic.md
      - Header Exchange: 3_rabbit/5_examples/4_header.md
  - NATS:
    - NATS Basics: 4_nats/1_nats-index.md
    - Routing: 4_nats/2_routing.md
    - Nats Pubslishing: 4_nats/3_publishing.md
  - Integrations: 5_integrations/1_integrations-index.md
  - FastAPI Plugin: 5_integrations/2_fastapi-plugin.md  
  - Contributing:
    - TODOS: 6_contributing/1_todo.md
    - Environment: 6_contributing/2_contributing-index.md
    - Documentation: 6_contributing/3_docs.md
    - Adapters: 6_contributing/4_adapters.md
  - Alternatives: 7_alternatives.md
  - Help Propan: 8_help.md
  - Release Notes: 9_CHANGELOG.md
